dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: P/cLVkNGvipTat08ITcaD5Hd+YWetaQQFMbWp0lKFByMPnKFqZTTNTZxF7kQUNQooVRgpqCQhDSNYllDOtUoGqaJoCnqzE2FohBAWqSDxpK6pYMJXrkXlekvQD1xvBeckB+92teTdI7z/nxl1LcU6JSPcVlAZhZsPPkY3JUecMh+kC7jTPjhobFB7nurhuoyqm2YuISufInrdodm36ZI2NJ7NL+uor1GbVcz2tGDHMYrkDg4+3dziKFKmt9ShK1s5jffuLBzC/woHFLszD0nZ3tuiTvJhrqF322ZJIdw0Z4fPft0IRWi9hbed2g/9ex7rK1GVV57/FIQFGc++6q6RtKHT6KR4u3gygtZaiaV187sPD0wikvkftlNmSujnS91e55XnizGFmjsursILZB+GV5ZkAss3Faq6uPi7e26Dl0kUVoUGvKeZaagau7cQsJOkAKZPGPOkIX/0p9UMfSie5iPym5YUULzKF87Oy2gpZYWti2XMHos6WadScCmB9gitBcmYp1nqPtd0s0Ya5V45xSnsgzBJEY4h+k4ZKRFS5x1OIcrHa/c9Itu1gqYYNYVnOJi3+oifTDt1vCtYvtAtGNPUZK637wiXOHJpm5Dh67rr7V1VcLnP7+C3CDDdOjHPDlrQTkhbXzvFsUOa4ZXvd8538R/wetgQtt5kefgz/o=
  file: Gerbers/LOG-100
  on:
    repo: w4xzr/LOG-100
  skip_cleanup: 'true'
